#!/usr/bin/env bash
# listen to nginx user
sudo pkill "apache2"
sudo sed -ri "s/[0-9]*?\sdefault_server/8080 default_server/" /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/nginx.conf /var/log/nginx/ /run/nginx.pid /var/lib/nginx/
sudo -u	nginx service nginx restart
